spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.74.157:3306/competition_beta?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: other
    password: other1s2b3